### ISSUE TITLE
Cannot find GHC on Windows or MacOS

### ISSUE THREAD

**Issue by AlexeyRaga** [actions/setup-haskell#1]
I am trying to use `setup-haskell` for my library CI, but I am getting this error when running on Windows or MacOS:

```
Run actions/setup-haskell@v1
##[error]Version 8.6.5 of ghc not found
##[error]Node run failed with exit code 1
```

I tried `GHC 8.6.5` and `GHC 8.4.4`, both have this problem.

Is there something that can be done to support Windows and MacOS (or at least just MacOS)?

**Comment by chshersh** [comment]
I have the same problems with GHC on Travis CI. I can specify `language: haskell` in my `.travis.yml` but it just doesn't know how to install Haskell on macOS and Windows :disappointed: So the workaround was to specify `language: c` and do a lot of `if`s to specify all installation instructions manually (which I never did because it's too tedious).

The only reliable way to install GHC on macOS I found is to use `ghcup`:

* https://www.haskell.org/ghcup/

And on Windows it's `chocolatey`:

* [The easiest way to setup a Haskell environment on Windows](https://hub.zhox.com/posts/introducing-haskell-dev/)

It would be so great if this action could support all three platforms so people can configure their CI and test Haskell projects on all 3 major platforms without much hassle!

**Comment by hvr** [comment]
Btw, over the last couple weeks I managed to get a working setup that handles Windows, macOS and Linux in a single GitHub action but its all in the workflow.yaml file; but my JavaScript skills aren't strong enough to hide all the boilerplate away into the `setup-haskell` action... :-/

**Comment by AlexeyRaga** [comment]
@chshersh that's what I was playing with too: https://github.com/haskell-works/avro/blob/github-workflow/.github/workflows/workflow.yml

**Comment by AlexeyRaga** [comment]
@hvr Great! Where can I see your `workflow.yaml`? I don't promise to contribute, but I have been working on Haskell CI on various systems and I am interested in subject.

**Comment by jared-w** [comment]
@AlexeyRaga,

I messaged @hvr after seeing a comment of his on r/haskell about the setup-haskell action and he showed me what he's been working on and where he got stuck (essentially bash -> JS). The current state of his workflow.yaml is [here](https://github.com/haskell-hvr/hackage-index/blob/master/.github/workflows/haskell.yaml). The tl;dr of what follows is that I'm going to translate the bash script to JS and hopefully that should essentially be all we need to do.

The most ideal solution, though, is to see if we can work with GitHub itself to upgrade their runners to include appropriate versions of GHC for every OS. I see this as another indicator that a tool like `ghcup` that supports all three operating systems would be _greatly_ desired. Rustup supports Windows, macOS, and Linux, and its full availability in GitHub's runners vs Ubuntu-only for GHC speaks volumes about the state of cross-platform automated GHC installs currently.

What follows is a very long summary and train of thought of how I arrived here. I went through the GitHub Actions documentation to understand the problem better and so what follows is probably old news for you both, but might be useful context for others:

---

This haskell setup repo uses some code that essentially does "nothing". This is because the workflow.yaml file will contain an "os: [ ubuntu-latest ]" or some declaration like that. The declaration corresponds to what runner is going to be used--in this case, the latest version of the GitHub hosted runner whose plethora of pre-installed software can be found [here](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#ubuntu-1804-lts). Finding that was the aha moment. Of course, the setup-haskell action doesn't need to do anything; the image already contains the software.

Well, except it doesn't on Windows and on macOS... Hence this issue. It *also* doesn't support every GHC version back down to v7.0--an omission Herbert was quick to point out [here](https://github.com/haskell-CI/haskell-ci/issues/310#issuecomment-546601014).

Lastly, caching. We would really like to cache downloading and installing GHC+cabal+whatever. We'd also like to cache the actual code stuff if we could. Unfortunately [the caching limitations](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/caching-dependencies-to-speed-up-workflows) are 400MB max per file, 2GB max per repo.

So, if a repo had Windows + macOS + Linux, you're looking at (in the very least) `~200-300MB x 3` just for GHC _per version_. And if you're trying to matrix test on multiple versions... Good luck. The better option for now seems to be to just worry about caching user code (Herbert setup a cache for cabal's nix-style store that its `new-*` commands uses).

---

So, summary of what we need/want:

* GHC + Cabal for GHC 7.0 - 8.8+
* On Windows, macOS, Linux
* [nice to have] free caching for code builds

And getting those things will be done by creating an action that:

1. Downloads the appropriate GHC and installs it
2. Downloads the appropriate cabal and installs it
3. Sets up the cache
4. Builds the code

All done in a way that

```yml
steps:
- uses: actions/checkout@master
- uses: insert_magic
  with:
    ghc-version: '8.6.5' # Exact version of ghc to use
    cabal-version: '3.0'
- run: runghc Hello.hs
```

works.

**Comment by hvr** [comment]
> Lastly, caching. We would really like to cache downloading and installing GHC+cabal+whatever. We'd also like to cache the actual code stuff if we could. Unfortunately the caching limitations are 400MB max per file, 2GB max per repo.

I'm not sure what you mean by "caching the actual code". If it's about caching the dist-newstyle/ folder I'm skeptical whether that's a good idea; over time it'd accumulate garbage when the project structure changes; also except for large projects such as Cabal or hackage-server it'd have rather modest gains; I typically only cache the nix-style ~/.cabal/store folder as everything else is often cheaper to download again (caching ~/.cabal/package is one of those very bad ideas for instance)

> - Sets up the cache

That's something people using other tooling-ecosystems also asked about; i.e. to have the cache-setup be controlled by another action; afaik that isn't currently possible. Maybe it's possible to merge `setup-haskell` w/ `actions/cache` but my approach is simply to have `setup-haskell` output the path to cache, which can then be fed as input into  `actions/cache` -- this also gives more flexibility for when you want to control the exact moment when the cache is retrieved; otherwise you wouldn't be able to perform any actions between ghc+cabal setup and the caching action.

**Comment by jared-w** [comment]
> I'm not sure what you mean by "caching the actual code".

I could've written that a little clearer. Caching `~/.cabal/store` is what I was referring to.

> That's something people using other tooling-ecosystems also asked about; i.e. to have the cache-setup be controlled by another action; afaik that isn't currently possible.

Ahh, that's disappointing. I'll look into setting up the path to the cache and having that be fed into `actions/cache`. Documenting that in a set of instructions would also be helpful to newcomers as well, so I'll see if I can do that.

**Comment by AlexeyRaga** [comment]
@hvr @jared-w is there any progress on this?

**Comment by jared-w** [comment]
> @hvr @jared-w is there any progress on this?

I've been stalled a bit due to on-boarding at a new job and the holidays taking the rest of my free time. My current progress is all up to date at [haskell-CI/setup](https://github.com/haskell-CI/setup/tree/bootstrap).

I think the immediate next tasks I have to do on it are:

1. Actually run the new code and make sure it at least works for linux
2. Replace any remaining echos or outputs with the proper logging using the SDK
3. (probably) iterate and fix macOS/windows.
4. Add back in ability to install different versions of cabal.

**Comment by jared-w** [comment]
@AlexeyRaga, I've recently had time to finally dig down into this and approach it with a new perspective.

Phyx has done phenomenal work in getting ghc to install on windows painlessly through chocolatey. In the meanwhile, `ghcup` has quickly become a very solid and reliable tool for linux and macOS. As such, I was able to save a significant amount of work by just utilizing them instead of trying to re-duplicate their logic.

The branch is a full and complete rewrite. I have it tested in GitHub Actions and can confirm that it works, which is very exciting.

Next tasks would be:

1. On Linux, I could be checking to see if the correct GHC and Cabal is already installed and essentially re-implement the no-op behavior of the current `actions/setup-haskell`. That would save some time for the common case, which is valuable.
2. Clean up the README, contributors, and other documentation.
3. See if I can work with GitHub to get GHC installed on macOS and Windows by default. Even having just the 1-2 most common versions would be a massive speed improvement for most people.

Thinking out-loud, it'd also be neat if ghcup and the chocolatey scripts could be used to install arbitrary GHC nightlies... But that can wait.

Oh, and last obvious step: Soliciting feedback and getting this merged into `haskell-CI/setup` and then hopefully up-streamed into `actions/setup-haskell` asap :)

**Comment by ferdodo** [comment]
I am having this issue as well on windows.

**Comment by hasufell** [comment]
I'm currently maintaining ghcup. Feel free to ping me if there's something necessary to improve for this issue. I'd also appreciate if someone pings me in case this actually makes it into github actions, so I'm aware of the impact of my changes and don't accidentially break a few hundred CIs.

**Comment by jared-w** [comment]
@hasufell I'll make sure to ping you when this makes it in, and I'll keep in touch with you and @Mistuke as necessary and generally keep you in the loop :)
